server:
  port: 9090 # random port


spring:
  application:
    name: order-service # tương ứng product-service / order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/order_service?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

grpc:
  client:
    product-service:
      address: static://localhost:50051
      negotiationType: plaintext
  server:
    enabled: false
